#version: '3.7'
version: '3.3'
services:
  iot-api:
    build:
      context: ./solar-api
    image: iot/solar-api
    container_name: solar-api
    restart: always
    volumes:
      - ${DIR}/solar-api:/app/logs
    ports:
      - "7001:7001"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      APP_PORT: 7001
      PROFILE: prod
      SPRING_PROFILES_ACTIVE: prod

  iot-front:
    build:
      context: ./solar-front
    image: iot/solar-front
    container_name: solar-front
    restart: always
    volumes:
      - ${DIR}/solar-front:/app/logs
    environment:
      DB_PASSWORD: ${DB_PASSWORD}