package com.phynos.framework.dao.mapper;

import com.phynos.framework.dao.model.RoleAction;
import com.phynos.framework.dao.model.RoleActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    long countByExample(RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    int deleteByExample(RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    int insert(RoleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    int insertSelective(RoleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    List<RoleAction> selectByExample(RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    RoleAction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleAction record, @Param("example") RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    int updateByExample(@Param("record") RoleAction record, @Param("example") RoleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    int updateByPrimaryKeySelective(RoleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_action
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    int updateByPrimaryKey(RoleAction record);
}