
com:
  phynos:
    solar:
      time: @timestamp@

server:
  port: 7001
  tomcat:
    uri-encoding: 'UTF-8'
  servlet:
    context-path: /

spring:
  application:
    name: SolarApi
  devtools:
    restart:
      enabled: false
  profiles:
    active: 'lupc'
  servlet:
    multipart:
      max-request-size: '10MB' # 上传文件总的最大值
      max-file-size: '10MB' # 单个文件的最大值
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    filter:
      order: 5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://42.192.126.212:7605/charger?useSSL=false&allowPublicKeyRetrieval=true
    #jdbc-url: jdbc:mysql://42.192.126.212:7605/charger?useSSL=false
    username: lupc
    password: 命令行输入

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml

# 日志配置
logging:
  config: classpath:logback-spring.xml
