com:
  phynos:
    solar:
      time: @timestamp@

# 认证配置
auth:
  secret: PDJ2544DEF4E55DF4D1
  expires: 7 #超时天数
  loginKaptcha: false
  registerKaptcha: true
  superPassword: Zhzf20220501
  excludePath:
    - /assets/**


# 文件存储
oss:
  url: http://42.192.126.212:7610/
  bucket: test
  accessKey: minioadmin
  secretKey: ${OSS_PASSWORD}

server:
  port: 7001
  tomcat:
    uri-encoding: 'UTF-8'
  servlet:
    context-path: /api

spring:
  application:
    name: SolarApi
  devtools:
    restart:
      enabled: false
  profiles:
    active: 'lupc'
  servlet:
    multipart:
      max-request-size: '10MB' # 上传文件总的最大值
      max-file-size: '10MB' # 单个文件的最大值
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    filter:
      order: 5
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://www.iotroll.com:7609/iotdb?useUnicode=true&characterEncoding=utf-8
    username: iot
    password: ${DB_PASSWORD}


mybatis-plus:
  global-config:
    db-config:
      schema: iot
  mapper-locations: classpath*:/mapper/*Mapper.xml

# 日志配置
logging:
  config: classpath:logback-spring.xml
