package com.phynos.framework.dao.model;

public class Action {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_action.id
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_action.remark
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_action.id
     *
     * @return the value of sys_action.id
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_action.id
     *
     * @param id the value for sys_action.id
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_action.remark
     *
     * @return the value of sys_action.remark
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_action.remark
     *
     * @param remark the value for sys_action.remark
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}