package com.phynos.framework.dao.model;

import java.util.Date;

public class Dict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.id
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.sort
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dict_label
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private String dictLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dict_value
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dict_type_id
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private Long dictTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.is_default
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private Boolean isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.status
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.created_datetime
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private Date createdDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.remark
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.id
     *
     * @return the value of sys_dict.id
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.id
     *
     * @param id the value for sys_dict.id
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.sort
     *
     * @return the value of sys_dict.sort
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.sort
     *
     * @param sort the value for sys_dict.sort
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dict_label
     *
     * @return the value of sys_dict.dict_label
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public String getDictLabel() {
        return dictLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dict_label
     *
     * @param dictLabel the value for sys_dict.dict_label
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setDictLabel(String dictLabel) {
        this.dictLabel = dictLabel == null ? null : dictLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dict_value
     *
     * @return the value of sys_dict.dict_value
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dict_value
     *
     * @param dictValue the value for sys_dict.dict_value
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dict_type_id
     *
     * @return the value of sys_dict.dict_type_id
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public Long getDictTypeId() {
        return dictTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dict_type_id
     *
     * @param dictTypeId the value for sys_dict.dict_type_id
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setDictTypeId(Long dictTypeId) {
        this.dictTypeId = dictTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.is_default
     *
     * @return the value of sys_dict.is_default
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.is_default
     *
     * @param isDefault the value for sys_dict.is_default
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.status
     *
     * @return the value of sys_dict.status
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.status
     *
     * @param status the value for sys_dict.status
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.created_datetime
     *
     * @return the value of sys_dict.created_datetime
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.created_datetime
     *
     * @param createdDatetime the value for sys_dict.created_datetime
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.remark
     *
     * @return the value of sys_dict.remark
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.remark
     *
     * @param remark the value for sys_dict.remark
     *
     * @mbg.generated Tue Nov 26 17:49:29 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}