package com.phynos.framework.dao.model;

import java.util.Date;

public class OperationLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.module_title
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String moduleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.action_name
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String actionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.method_name
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.method_params
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String methodParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.status
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.oper_user_id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Long operUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.oper_URL
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String operUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.oper_IP
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String operIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.oper_location
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String operLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.error_msg
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String errorMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operation_log.operation_datetime
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Date operationDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.id
     *
     * @return the value of sys_operation_log.id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.id
     *
     * @param id the value for sys_operation_log.id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.module_title
     *
     * @return the value of sys_operation_log.module_title
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getModuleTitle() {
        return moduleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.module_title
     *
     * @param moduleTitle the value for sys_operation_log.module_title
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setModuleTitle(String moduleTitle) {
        this.moduleTitle = moduleTitle == null ? null : moduleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.action_name
     *
     * @return the value of sys_operation_log.action_name
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.action_name
     *
     * @param actionName the value for sys_operation_log.action_name
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.method_name
     *
     * @return the value of sys_operation_log.method_name
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.method_name
     *
     * @param methodName the value for sys_operation_log.method_name
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.method_params
     *
     * @return the value of sys_operation_log.method_params
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getMethodParams() {
        return methodParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.method_params
     *
     * @param methodParams the value for sys_operation_log.method_params
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setMethodParams(String methodParams) {
        this.methodParams = methodParams == null ? null : methodParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.status
     *
     * @return the value of sys_operation_log.status
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.status
     *
     * @param status the value for sys_operation_log.status
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.oper_user_id
     *
     * @return the value of sys_operation_log.oper_user_id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Long getOperUserId() {
        return operUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.oper_user_id
     *
     * @param operUserId the value for sys_operation_log.oper_user_id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setOperUserId(Long operUserId) {
        this.operUserId = operUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.oper_URL
     *
     * @return the value of sys_operation_log.oper_URL
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getOperUrl() {
        return operUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.oper_URL
     *
     * @param operUrl the value for sys_operation_log.oper_URL
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setOperUrl(String operUrl) {
        this.operUrl = operUrl == null ? null : operUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.oper_IP
     *
     * @return the value of sys_operation_log.oper_IP
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getOperIp() {
        return operIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.oper_IP
     *
     * @param operIp the value for sys_operation_log.oper_IP
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setOperIp(String operIp) {
        this.operIp = operIp == null ? null : operIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.oper_location
     *
     * @return the value of sys_operation_log.oper_location
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getOperLocation() {
        return operLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.oper_location
     *
     * @param operLocation the value for sys_operation_log.oper_location
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setOperLocation(String operLocation) {
        this.operLocation = operLocation == null ? null : operLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.error_msg
     *
     * @return the value of sys_operation_log.error_msg
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.error_msg
     *
     * @param errorMsg the value for sys_operation_log.error_msg
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operation_log.operation_datetime
     *
     * @return the value of sys_operation_log.operation_datetime
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Date getOperationDatetime() {
        return operationDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operation_log.operation_datetime
     *
     * @param operationDatetime the value for sys_operation_log.operation_datetime
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setOperationDatetime(Date operationDatetime) {
        this.operationDatetime = operationDatetime;
    }
}