package com.phynos.framework.dao.model;

import java.util.Date;

public class Parameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.para_label
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String paraLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.para_key
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String paraKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.para_value
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String paraValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.para_type
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Integer paraType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.created_datetime
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Date createdDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.created_user_id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Long createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.update_datetime
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Date updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.update_user_id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private Long updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.remark
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.id
     *
     * @return the value of sys_parameter.id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.id
     *
     * @param id the value for sys_parameter.id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.para_label
     *
     * @return the value of sys_parameter.para_label
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getParaLabel() {
        return paraLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.para_label
     *
     * @param paraLabel the value for sys_parameter.para_label
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setParaLabel(String paraLabel) {
        this.paraLabel = paraLabel == null ? null : paraLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.para_key
     *
     * @return the value of sys_parameter.para_key
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getParaKey() {
        return paraKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.para_key
     *
     * @param paraKey the value for sys_parameter.para_key
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setParaKey(String paraKey) {
        this.paraKey = paraKey == null ? null : paraKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.para_value
     *
     * @return the value of sys_parameter.para_value
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getParaValue() {
        return paraValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.para_value
     *
     * @param paraValue the value for sys_parameter.para_value
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setParaValue(String paraValue) {
        this.paraValue = paraValue == null ? null : paraValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.para_type
     *
     * @return the value of sys_parameter.para_type
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Integer getParaType() {
        return paraType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.para_type
     *
     * @param paraType the value for sys_parameter.para_type
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setParaType(Integer paraType) {
        this.paraType = paraType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.created_datetime
     *
     * @return the value of sys_parameter.created_datetime
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.created_datetime
     *
     * @param createdDatetime the value for sys_parameter.created_datetime
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.created_user_id
     *
     * @return the value of sys_parameter.created_user_id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Long getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.created_user_id
     *
     * @param createdUserId the value for sys_parameter.created_user_id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.update_datetime
     *
     * @return the value of sys_parameter.update_datetime
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.update_datetime
     *
     * @param updateDatetime the value for sys_parameter.update_datetime
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.update_user_id
     *
     * @return the value of sys_parameter.update_user_id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.update_user_id
     *
     * @param updateUserId the value for sys_parameter.update_user_id
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.remark
     *
     * @return the value of sys_parameter.remark
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.remark
     *
     * @param remark the value for sys_parameter.remark
     *
     * @mbg.generated Thu Sep 26 09:31:07 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}