server:
  port: 9873
  tomcat:
    uri-encoding: 'UTF-8'

spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: 'dev'
  servlet:
    multipart:
      max-request-size: '10MB' # 上传文件总的最大值
      max-file-size: '10MB' # 单个文件的最大值

logging:
  level:
    com:
      spring: trace